name: Unit test
permissions:
  contents: read
on:
  push:
    branches: [ "master" ]
    paths:
      - "*.pyx"
      - "*.cpp"
      - "*.py"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "*.pyx"
      - "*.cpp"
      - "*.py"
      - ".github/workflows/ci.yml"
jobs:
  pytests:
    strategy:
      fail-fast: false
      matrix:  # https://github.com/actions/python-versions/releases
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.13t", "3.14", "3.14t"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - run: python3 -m pip install --upgrade pip
      - run: pip install pytest pytest-asyncio
      - run: pip install --editable .
      - run: pytest
      - if: matrix.python-version == '3.13t' || matrix.python-version == '3.14t'
        run: |
          pip install pytest-run-parallel
          pytest --iterations=4 --parallel-threads=auto
